function createfigure(cdata1,titlestring)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 04-May-2015 13:45:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','Layer','top',...
    'CLim',[0.01 0.4],...
    'YDir','reverse');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 130]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 125.5]);
box(axes1,'on');
hold(axes1,'on');

% Create title
title(titlestring);

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create colorbar
colorbar('peer',axes1);

